#pragma once

/*Define all ID's*/
/*INFO: all TAB-ID's get a leading 1*/
#define TAB_CONTOL_ID 101

/*INFO: all MENU-ID's get a leading 2*/
#define MENU_DATA_NEW_TASK_ID 201
#define MENU_DATA_EXIT_ID 202

#define MENU_OPT_ALWAYS_PRIO_ID 210
#define MENU_OPT_MIN_START_ID 211
#define MENU_OPT_CLOSE_MIN_ID 212

#define MENU_OPT_TAB_PROC 2131
#define MENU_OPT_TAB_POW 2132
#define MENU_OPT_TAB_HIST 2133
#define MENU_OPT_TAB_AST 2134
#define MENU_OPT_TAB_USR 2135
#define MENU_OPT_TAB_DET 2136
#define MENU_OPT_TAB_SER 2137

#define MENU_OPT_FULL_ACN 214
#define MENU_OPT_FULL_PROG_HIST 215

#define MENU_VIEW_UPTD_NOW_ID 220
#define MENU_VIEW_SPD_HIGH_ID 2210	/*SPD => SPEED*/
#define MENU_VIEW_SPD_NORM_ID 2211
#define MENU_VIEW_SPD_LOW_ID 2212
#define MENU_VIEW_SPD_STOP_ID 2213

#define MENU_VIEW_GRP_TYPE_ID 216
#define MENU_VIEW_EXP_ALL_ID 217
#define MENU_VIEW_DECR_ALL_ID 218